Blank/Blank.xcodeproj/project.pbxproj, Blank/Blank/BlankApp.swift, Blank/Blank/CoreData/Blank.xcdatamodeld/Blank.xcdatamodel/contents, Blank/Blank/CoreData/Persistence.swift, Blank/Blank/View/PersistenceView.swift
코어 데이터 초기화 및 모델을 추가했습니다.
- 코어 데이터 모델 생성
- 코어 데이터 관리 컨트롤러 (`PersistenceController`) 추가
```diff
+ struct PersistenceController {...}
```
- #10
=> [Feat] 코어 데이터 모델 추가

Blank/Blank.xcodeproj/project.pbxproj, Blank/Blank/View/ImageView.swift, Blank/Blank/View/PinchZoomView.swift
- ImageView
- Image 및 컴포넌트(TextField, Button 등)을 올리는 View
- PinchZoomView 
- PinchZoom 기능을 적용한 View 
```swift
var magnification: some Gesture {
// PinchZoom Gesture
MagnificationGesture()
// 확대 시작 시
.onChanged { state in
adjustScale(from: state)
}
// 확대 종료 시
.onEnded { state in
withAnimation {
validateScaleLimits()
}
lastScale = 1.0
}
}
```
=> [Feat] PinchZoom view 추가

Blank/Blank.xcodeproj/project.pbxproj, Blank/Blank/BlankApp.swift, Blank/Blank/View/ContentView.swift, Blank/Blank/View/CurrentPageView.swift, Blank/Blank/View/Home/HomeView.swift, Blank/Blank/View/OCREditView.swift, Blank/Blank/View/OverView.swift, Blank/Blank/View/OverViewModalView.swift, Blank/Blank/View/ResultPageView.swift, Blank/Blank/View/TestPageView.swift, Blank/Blank/View/WordSelectView.swift, Blank/Blank/ViewModel/HomeViewModel.swift, Blank/Blank/ViewModel/OverViewModel.swift
- PDFview 의 페이지를 이미지로 변환하는 기능
- 각 페이지 썸네일로 활용해서 모달뷰나 하단 스크롤뷰 기능 구현
- 각 페이지에 이미지를 pdf에서 변환한 이미지로 교체
- 
- 파일 로드시 로딩 뷰 구현
- PDF 페이지 이미지로 리턴 기능
- 오버뷰에 PDFView 구현해서 해당 페이지 이미지로 보여주기
- 하단 스크롤바 구현 및 페이지 선택 시 해당 페이지로 이동, 선택페이지는 스크롤바 가운데로 이동
- 스크롤바 및 모달 뷰에서 페이지 선택될 시 파란색으로 테두리 처리
- 모달 뷰 구현
- 다른 페이지들 pdf 페이지를 이미지로 바꾼 것으로 대체
```diff
```
=> [Design][Feat] 모든뷰 이미지로 수정 및 scrollview 기능 추가

Blank/Blank.xcodeproj/project.pbxproj, Blank/Blank/View/OCREdit/TextView.swift, Blank/Blank/View/TestPage/TestPageImageView.swift, Blank/Blank/View/TestPage/TestPagePinchZoomView.swift, Blank/Blank/View/TestPage/TestPageView.swift
testpageview image 및 pinchzoom 적용
testpageview image 및 pinchzoom 적용
font 사이즈 고정
=> 48 design testpageview image 및 pinchzoom 적용

Blank/Blank/View/OCREdit/OCREditView.swift, Blank/Blank/View/OCREdit/OCRImageView.swift, Blank/Blank/View/OCREdit/OCRPinchZoomView.swift, Blank/Blank/View/OverView.swift, Blank/Blank/View/TestPage/TestPageImageView.swift, Blank/Blank/View/TestPage/TestPagePinchZoomView.swift, Blank/Blank/View/TestPage/TestPageView.swift
viewModal page구조체로 변경
(해당뷰)
OCREditView, TestView
OCREditView, TestView page 구조체로 변경
=> [feat] viewModal page구조체로 변경

Blank/Blank.xcodeproj/project.pbxproj, Blank/Blank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Blank/Blank/View/WordSelectView.swift
- `WordSelectView`에서 현재 Alert을 토스트 헝태로 변경
- `WordSelectView`에서 현재 Alert을 토스트 헝태로 변경
- SPM 외부 라이브러리를 사용하였습니다: https://github.com/exyte/PopupView
=> [Feat] WordSelectView의 Alert을 Toast로 바꿈

Blank/Blank/ViewModel/ScoringViewModel.swift
- 채점 로직 변경
- 채점시에는 대소문자 구분없이 글자만 같으면 정답으로 처리한다.
- 띄어쓰기 입력은 받되 채점시 고려안함,
- `.` 과 `,` 및 `…`(점 세개 입력하면 자동 완성되는 문자) 도 입력은 받되 채점시 고려 안함
```swift
// 채점 로직:
// 1) 채점시에는 대소문자 구분없이 글자만 같으면 정답으로 처리한다.
// 2) 띄어쓰기 입력은 받되 채점시 고려안함
// 3) [ . ] , [ , ] 도 입력은 받되 채점시 고려 안함
let replacingRegex = "([ .,…])"
let currentWordValue = currentWord.wordValue
.lowercased()
.replacingOccurrences(of: replacingRegex, with: "", options: .regularExpression)
let targetWordValue = targetWords[targetWordIndex].wordValue
.lowercased()
.replacingOccurrences(of: replacingRegex, with: "", options: .regularExpression)
targetWords[targetWordIndex].isCorrect = currentWordValue == targetWordValue
```
=> [Feat] 채점 로직 변경

Blank/Blank/Util/NavigatioinUtil.swift, Blank/Blank/View/OverView/OverView.swift, Blank/Blank/View/ResultPageView.swift
- 마지막페이지에서 '페이지 선택으로 이동'을 클릭시 앱이 종료되는 버그가 있어서, 이를 fix함
- 어디서 문제가 발생한 것인지 파악
- 코드 수정
```diff
+ static func popToOverView(animated: Bool = false) {
+            guard let navigationController = findNavigationController(viewController: +UIApplication.shared.connectedScenes.flatMap { ($0 as? UIWindowScene)?.windows ?? [] }.first { $0.isKeyWindow +}?.rootViewController) else {
+               return
+            }
+            
+            if navigationController.viewControllers.count > 1 {
+                let overViewController = navigationController.viewControllers[1]  // 루트 뷰 바로 다음에 있는 뷰 컨트롤러를 가져옵니다.
+                navigationController.popToViewController(overViewController, animated: animated)
+            }
+        }
```
=> [Fix] 페이지선택으로 이동 버튼 눌렀을때 앱이 꺼지는 버그 해결

Blank/Blank/View/OCREdit/OCREditView.swift, Blank/Blank/View/OCREdit/OCRImageView.swift, Blank/Blank/View/OCREdit/ScrribleModalView.swift, Blank/Blank/View/OCREdit/ScrribleVideoView.swift, Blank/Blank/View/OCREdit/TextView.swift, Blank/Blank/View/TestPage/TestPageImageView.swift, Blank/Blank/View/TestPage/TestPageView.swift
OCRImageView 및 TestPageImageView에서 TexiView 불러오는 방법 뷰모델 적용하여 변경
textView viewModel 인자로 변경 및 binding 필요 없는 값들은 binding 삭제하여 보라색 에러 삭제
- textView 생성 시 뷰모델 활용
```swift
.overlay {
ForEach(wordSelectViewModel.selectedWords.indices, id: \.self) { index in
let box = adjustRect(wordSelectViewModel.selectedWords[index].rect, in: proxy)
let real = wordSelectViewModel.selectedWords[index].id
TextView(name: $wordSelectViewModel.selectedWords[index].wordValue, height: box.height, width: box.width, orinX: real)
.position(CGPoint(x: box.origin.x + (box.width / 2), y: (box.origin.y + (box.height / 2 ))))
}
}
```
- Binding 제거하여 보라색 에러문구 삭제
```swift
struct TextView: View {
@State var isFocused: Bool = false
@Binding var name: String
var height: CGFloat // binding제거
var width: CGFloat // binding제거
var …
```
=> 93 feat bug textfield viewmodel 적용 및 버그 픽스

Blank/Blank/View/ImageView.swift, Blank/Blank/View/OverView/OverViewModalView.swift, Blank/Blank/View/WordSelectView.swift
- 워드셀렉트뷰에서 단어를 선택해야지 다음 뷰로 넘어갈 수 있게 설정했습니다.
<image src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExY3d3aWpicjR1bDgwOHQzNWIzcjBmZTd4dGtvd202d3J3czdkb3Q5biZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/M7XPzewq5qgN1kOYY8/giphy.gif">
```diff
```
=> [Feat] 워드셀렉트뷰에서 단어가 하나라도 선택되어야 다음 페이지로 이동가능하게 구현

Blank/Blank/View/OverView/OverView.swift
- 오버뷰에서 결과보기 중 내가 원하는 회차를 클릭하면 클릭한 회차가 라벨에 보이게 설정
<image src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM3Bldmw3aWFwdmhuM3pmdHExNGhsZTk4ZW80NXJmeTBubmRwZjl3ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fb9ANzmcHON3AmQMWH/giphy.gif">
```diff
```
=> [Feat] 오버뷰에서 결과보기 클릭시 내가 클릭한 회차를 버튼 라벨에 보여지게함

Blank/Blank/View/OverView/OverView.swift, Blank/Blank/ViewModel/OverViewModel.swift
#103 
- 원본 보기 기능
- 회차 기능 사용시 특정 회차를 선택한 상태에서 다른 페이지 섬네일을 터치한 경우 단어 표시 영역이 사라지지 않는 문제
- 원본 기능 구현
- 버그 픽스
https://github.com/DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank/assets/40187546/9cb98402-76ab-4d4a-8e89-aadb6b4d9a17
=> [Feat] OverView에서 페이지 전환시 표시 영역 지움 + '원본' 기능 구현

Blank/Blank/View/OverView/OverView.swift
- 오버뮤에서 페이지를 텍스트필드에 입력할때 키보드가 올라와서 앱의 비율을 망치는 버그를 수정했습니다.
```diff
```
=> [Fix] 오버뷰에서 키보드가 화면을 잡아먹으면서 뜨지 않게 버그 수정

Blank/Blank.xcodeproj/project.pbxproj, Blank/Blank/Util/RecognizeText.swift, Blank/Blank/View/ImageView.swift, Blank/Blank/View/OverView/OverVIewImageView.swift, Blank/Blank/ViewModel/OverViewModel.swift
- 기존 글자인식을 할 때 [ brown 밤색의 , 밤색 ] 이라는 글자들이 있으면 "밤색"이라는 글자가 동일한 단어로 인식해서
"밤색의" 와 "밤색" 이 동일 좌표를 갖게 됨
- 해당 글자들을 좌표를 각각 다르게 갖게 하려고 함
- 로직 수정 
- 단어마다 시작과 끝을 저장해서 단어별로 구별되게 함 
- 구별된 단어를 바탕으로 인식 좌표를 할당
- 해당과정에서 RecognizeText함수를 global 함수의 형태로 별도 파일 생성 (RecognizeText.swift)
- OverViewModel 의  RecognizeText함 수정 및 이동
-  <img width="1495" alt="overViewModel 글자인식" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank/assets/42464602/bc433816-ccf9-473a-af54-9361dc689476">
-  ImageView RecognizeText함 수정 및 이동
- <img width="1484" alt="스크린샷 2023-11-07 오후 5 09 03" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank/assets/42464602/96eb1d29-45d2-440a-93fe-5d7eed67337f">
```diff
func recognizeText(from image: UIImage, …
```
=> [Bug]-fixed 단어 인식시 동일한 글자가 있을경우 좌표를 제대로 인식하지 못하는 버그 수정

Blank/Blank/Util/RecognizeText.swift
- 글자 인식시 좌표반환 값이 소수점 14자리까지 존재
- 연산으로 인한 앱실행시 발열의심
- 소수점 14자리를 잘라 연산을 감소시킴
- 소수점 2,3자리 및 정수 일때 확인
- 정수일때와 소수점일때 모두 빈칸 표시에 크게 영향이 없음
- 아예 정수로 하고 싶지만 CGRect자체가 Floating포인트를 가지고 있는 형태로 Struct를 구성해놓아서 소수점 1자리(0으로) 만듦 
```diff
+ recognizeText()에 아래 내용 추가
let changeFalotingToIntBox = CGRect(
x: Int(round(boundingBox.origin.x)),
y: Int(round(boundingBox.origin.y)),
width: Int(round(boundingBox.width)),
height: Int(round(boundingBox.height))
)
recognizedTexts.append((String(word), changeFalotingToIntBox))
```
=> [Enhancement] 글자 인식시 좌표 연산 부분 개선완료

Blank/Blank.xcodeproj/project.pbxproj, Blank/Blank/Util/PencilDobuleTapInteractionView.swift, Blank/Blank/View/WordSelectView.swift
- 앱 사용시 pencil 사용이 필수
- pencil사용할 경우 일반적인 User는 pencil double tap을 자주 활용
- Word 선택 - 선택해제간에 버튼으로 전환이 아닌 Double Tap으로 전환기능 구현
- 순수 SwiftUI만으로는 Pencil Double tap 구현불가
- UIKitRepresentable 방식으로 구현
- docs에 안내된 내용으로는 User의 탭 시 선호하는 동작을 먼저 확인하고 원하는 동작을 선택할 수 있게 해주는 방식을 추천
- 그러나 우리 앱의 WordSelectView에서 단어선택 및 해제 전환간 별도의 동작을 사용자가 할 수 있는게 없으므로
Double Tap시 버튼 toggle 기능으로 부여 
- PencilDobuleTapInteractionView 파일 추가 
- WordSeleceView에 representable 내용 추가
- 아래 코드는  WordSeleceView 추가 내용
```diff
PencilDobuleTapInteractionView {
// 이 클로저는 pencil 더블 탭 시 실행
self.isSelectArea.toggle()
}
.frame(width: 0, height: 0) // 뷰 자체 크기를 없애서 Double Tap동작에 대한 기능만 추가
```
=> [feat] pencil double tap시 단어선택- 선택지우기 버튼간 변환구현

Blank/Blank.xcodeproj/project.pbxproj, Blank/Blank/BlankApp.swift, Blank/Blank/Util/ImageUtil.swift, Blank/Blank/Util/RecognizeText.swift, Blank/Blank/ViewModel/OverViewModel.swift
#117 
- 이미지 불러올 시 비율 일정하게(안정된 비율 => A4로 설정했습니다.)
- **가로가 더 긴 페이지를 불러와도 정상 작동해서 막기 기능은 넣지 않았습니다.**
- 이미지로 로딩시 비율 맞추기
- OverViewModel의 generateCurrentImage() 의 maxWidth를 더 낮게 조정하면 보다 정확한 area 값을 얻을 수 있습니다. 
- 그만큼 해상도는 더 낮아집니다.
```swift
func generateCurrentImage() {
guard let page = pdfDocument.page(at: currentPage - 1) else {
return
}
// TODO: - 더 큰 해상도도 정확히 인식할 수 있어야 함
// 현재 가로 해상도 최대 600을 넘어가면 범위 어긋남
let maxWidth: CGFloat = 620 // 최대 크기를 더 늘릴 수 있다면 늘려보기
let maxHeight: CGFloat = maxWidth * 1.414
```
```plain
samplepdf.pdf
pageRect.size (612.0, 864.0)
height = width * 1.4117647059
toeic.pdf
pageRect.size (595.32, 841.9200000000001)
height = width * 1.4142310018
elementarySchool.pdf
pageRect.size (595.5, 842.25)
height = width * 1.4143576826
sample.pdf
pageRect.size (595.2756, 841.8898) …
```
=> [Feat] 이미지 여백 늘리기 기능

Blank/Blank/ViewModel/OverViewModel.swift
(cherry picked from commit ccabbfec0ffeede3373fd724918ea084f2c73a30)
#124 
```diff
- let page = pages[index]
- let lastSessionNumber = try CDService.shared.loadAllSessions(of: page).count
- return lastSessionNumber
+ if let page = pages.first(where: { $0.currentPageNumber == index + 1} ) {
+    let lastSessionNumber = try CDService.shared.loadAllSessions(of: page).count
+    return lastSessionNumber
+  }
```
=> [Fix] loadLastSessionNumber 배열 범위초과 에러 해결

Blank/Blank.xcodeproj/project.pbxproj, Blank/Blank/Extension/Color+.swift, Blank/Blank/View/ImageView.swift, Blank/Blank/View/OCREdit/OCREditView.swift, Blank/Blank/View/OverView/OverView.swift, Blank/Blank/View/OverView/OverViewModalView.swift, Blank/Blank/View/ResultPage/ResultPageView.swift, Blank/Blank/View/TestPage/TestPageView.swift, Blank/Blank/View/WordSelectView.swift, Blank/Blank/ViewModel/OverViewModel.swift
- 알러트 내용 변경
- 네비게이션 뷰 타이틀 변경
- 이미지 화질 개선
- 배경색 전부 통일
```diff
```
=> #146 design 뷰제목 및 알러트 단어 바꾸기

Blank/Blank/View/Home/FolderThumbnailView.swift, Blank/Blank/View/Home/HomeView.swift, Blank/Blank/View/Home/PDFThumbnailView.swift, Blank/Blank/View/Home/SelectFolderView.swift, Blank/Blank/View/ImageView.swift, Blank/Blank/View/OverView/OverVIewImageView.swift, Blank/Blank/View/OverView/OverView.swift, Blank/Blank/View/OverView/OverViewModalView.swift, Blank/Blank/View/WordSelectView.swift, Blank/Blank/ViewModel/HomeViewModel.swift
- 홈뷰의 파일의 텍스트 크기 조절
- 네비게이션 타이틀에 현재 폴더 이름이 뜨게 설정
- 오버뷰 모달뷰 데이터 표시 방법 변경
- 파일, 폴더 추가 버튼 재설정
- 폴더 디자인 변경
- 미니에서 보이는  텍스트 크기
```diff
```
=> #152 design UI변경
